<?php
class CrudService{
 public static function safeTable($table){$m=entity_map();if(!isset($m[$table]))throw new InvalidArgumentException('Unknown entity');return $m[$table];}
 public static function list($table,$search='',$limit=25,$offset=0){$m=self::safeTable($table);$cols=implode(',',array_map(fn($x)=>'`'.$x.'`',$m['columns']));$sql="SELECT {$cols} FROM `{$m['table']}`";$where=[];$args=[];if(!empty($m['soft_delete']))$where[]='deleted_at IS NULL';if($search&&!empty($m['search'])){$p=[];foreach($m['search'] as $c){$p[]="`{$c}` LIKE ?";$args[]='%'.$search.'%';}$where[]='('.implode(' OR ',$p).')';}if($where)$sql.=' WHERE '.implode(' AND ',$where);$sql.=' ORDER BY `'.$m['order_by'].'` DESC LIMIT '.(int)$limit.' OFFSET '.(int)$offset;$q=db()->prepare($sql);$q->execute($args);return $q->fetchAll();}
 public static function count($table,$search=''){ $m=self::safeTable($table);$sql="SELECT COUNT(*) FROM `{$m['table']}`";$w=!empty($m['soft_delete'])?' WHERE deleted_at IS NULL':'';$args=[];if($search&&!empty($m['search'])){$p=[];foreach($m['search'] as $c){$p[]="`{$c}` LIKE ?";$args[]='%'.$search.'%';}$w.=($w?' AND ':' WHERE ').'('.implode(' OR ',$p).')';}$q=db()->prepare($sql.$w);$q->execute($args);return (int)$q->fetchColumn();}
 public static function delete($table,$id,$hard=false){$m=self::safeTable($table);if(!empty($m['soft_delete'])&&!$hard){$q=db()->prepare("UPDATE `{$m['table']}` SET deleted_at=NOW(),deleted_by=? WHERE id=?");$q->execute([actor_id(),$id]);}else{$q=db()->prepare("DELETE FROM `{$m['table']}` WHERE id=?");$q->execute([$id]);}AuditService::log($hard?'HARD_DELETE':'DELETE',$table,$id,'CRUD delete');}
 public static function restore($table,$id){$m=self::safeTable($table);if(empty($m['soft_delete']))return;$q=db()->prepare("UPDATE `{$m['table']}` SET deleted_at=NULL,deleted_by=NULL WHERE id=?");$q->execute([$id]);AuditService::log('RESTORE',$table,$id,'CRUD restore');}
}
function entity_map(){if(!isset($GLOBALS['ENTITY_MAP']))$GLOBALS['ENTITY_MAP']=require __DIR__.'/../admin/entity_map.php';return $GLOBALS['ENTITY_MAP'];}
