<?php
require_once __DIR__.'/../includes/bootstrap.php'; require_perm('admissions.manage'); check_csrf();
function enroll_admission($id){
 $q=db()->prepare('SELECT * FROM admissions WHERE id=?');$q->execute([$id]);$a=$q->fetch();if(!$a)throw new RuntimeException('Admission not found');
 if($a['status']==='Admitted') return 'Already admitted';
 db()->beginTransaction();
 try{
  $email=$a['email']; $exists=db()->prepare('SELECT id FROM users WHERE email=?');$exists->execute([$email]);if($exists->fetch())throw new RuntimeException('An account already exists for this email. Review manually.');
  $role=db()->query("SELECT id FROM roles WHERE name='Student'")->fetchColumn();$pw='Student@'.substr(strtoupper(hash('sha256',$a['application_no'])),0,8);
  $u=db()->prepare('INSERT INTO users(role_id,name,email,password_hash) VALUES(?,?,?,?)');$u->execute([$role,$a['full_name'],$email,password_hash($pw,PASSWORD_DEFAULT)]);$uid=(int)db()->lastInsertId();
  $dept=db()->query("SELECT id FROM departments ORDER BY id LIMIT 1")->fetchColumn();$branch=db()->query("SELECT id FROM branches ORDER BY id LIMIT 1")->fetchColumn();$course=db()->query("SELECT id FROM courses ORDER BY id LIMIT 1")->fetchColumn();$ay=db()->query("SELECT id FROM academic_years WHERE is_current=1 LIMIT 1")->fetchColumn();$sem=db()->query("SELECT id FROM semesters ORDER BY number LIMIT 1")->fetchColumn();$div=db()->query("SELECT id FROM divisions ORDER BY id LIMIT 1")->fetchColumn();
  $enr='STU'.date('Y').str_pad((string)$uid,6,'0',STR_PAD_LEFT);$st=db()->prepare('INSERT INTO students(user_id,enrollment_no,admission_no,department_id,branch_id,course_id,academic_year_id,semester_id,division_id,admission_date) VALUES(?,?,?,?,?,?,?,?,?,CURDATE())');$st->execute([$uid,$enr,$a['application_no'],$dept,$branch,$course,$ay,$sem,$div]);$sid=(int)db()->lastInsertId();
  $fs=db()->query("SELECT id FROM fee_structures WHERE status='Active' ORDER BY id DESC LIMIT 1")->fetchColumn();if($fs){$amt=(float)db()->query("SELECT total_amount FROM fee_structures WHERE id=".(int)$fs)->fetchColumn();db()->prepare('INSERT INTO student_fees(student_id,fee_structure_id,category,amount,due_date,status) VALUES(?,?,?,?,DATE_ADD(CURDATE(),INTERVAL 30 DAY),\'Pending\')')->execute([$sid,$fs,'Admission/Fee',max(0,$amt)]);}
  db()->prepare("UPDATE admissions SET status='Admitted' WHERE id=?")->execute([$id]);db()->prepare('INSERT INTO notifications(user_id,title,message,type,link) VALUES(?,?,?,?,?)')->execute([$uid,'Admission Approved','Your digital college account has been created. Username: '.$email.' Password: '.$pw,'success','/student/index.php']);db()->commit();AuditService::log('ADMISSION_ENROLL','admissions',$id,'Created student '.$enr);return 'Admitted and enrolled. Login: '.$email.' / '.$pw;
 }catch(Throwable $e){db()->rollBack();throw $e;}
}
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['approve_id'])){try{$msg=enroll_admission((int)$_POST['approve_id']);$_SESSION['flash']=['success',$msg];}catch(Throwable $e){$_SESSION['flash']=['danger',$e->getMessage()];}redirect('admissions.php');}
$rows=db()->query('SELECT * FROM admissions ORDER BY id DESC')->fetchAll();page_top('Online Admissions & Digital Enrollment');flash();?><div class="card p-3 mb-3"><a class="btn btn-primary" href="../public/admission.php" target="_blank">Open Public Admission Portal</a></div><div class="card p-3 table-responsive"><table class="table align-middle"><tr><th>Application</th><th>Applicant</th><th>Program</th><th>Branch</th><th>Status</th><th>Action</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['application_no'])?></td><td><?=e($r['full_name'])?><br><small><?=e($r['email'])?></small></td><td><?=e($r['program'])?></td><td><?=e($r['branch'])?></td><td><span class="badge bg-secondary"><?=e($r['status'])?></span></td><td><?php if($r['status']!=='Admitted'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="approve_id" value="<?=e($r['id'])?>"><button class="btn btn-sm btn-success" onclick="return confirm('Approve and automatically create the student identity, academic record and fee record?')">Approve & Enroll</button></form><?php else:?>Completed<?php endif;?></td></tr><?php endforeach;?></table></div><?php page_bottom();
