<?php
require_once __DIR__.'/../includes/bootstrap.php';require_login();check_csrf();
$ENTITY_MAP=require __DIR__.'/entity_map.php';$GLOBALS['ENTITY_MAP']=$ENTITY_MAP;
$e=$_GET['e']??'students';if(!isset($ENTITY_MAP[$e])){http_response_code(404);exit('Unknown entity');}
$meta=$ENTITY_MAP[$e];$meta['has_id']=$meta['has_id']??in_array('id',$meta['columns'],true);$meta['read_only']=$meta['read_only']??false;require_perm($meta['perm']);
$search=trim($_GET['q']??'');$page=max(1,(int)($_GET['page']??1));$limit=min(100,max(5,(int)($_GET['limit']??25)));$rows=CrudService::list($e,$search,$limit,($page-1)*$limit);$total=CrudService::count($e,$search);
page_top($meta['label']);flash();
?>
<div class="card p-3 mb-3"><div class="d-flex flex-wrap gap-2"><form class="d-flex gap-2 flex-grow-1"><input type="hidden" name="e" value="<?=e($e)?>"><input class="form-control" name="q" value="<?=e($search)?>" placeholder="Search <?=e($meta['label'])?>"><select name="limit" class="form-select" style="max-width:130px"><option>25</option><option value="50" <?=($limit===50?'selected':'')?>>50</option><option value="100" <?=($limit===100?'selected':'')?>>100</option></select><button class="btn btn-primary">Search</button></form><?php if(!$meta['read_only']):?><a class="btn btn-success" href="create.php?e=<?=urlencode($e)?>">+ Add</a><?php endif;?><a class="btn btn-outline-secondary" href="../reports/export.php?e=<?=urlencode($e)?>&format=xls">Excel</a><a class="btn btn-outline-secondary" href="../reports/export.php?e=<?=urlencode($e)?>&format=pdf">PDF</a></div></div>
<div class="table-responsive card"><table class="table align-middle mb-0"><thead><tr><?php foreach($meta['columns'] as $c):?><th><?=e(ucwords(str_replace('_',' ',$c)))?></th><?php endforeach;?><th>Actions</th></tr></thead><tbody>
<?php foreach($rows as $r):?><tr><?php foreach($meta['columns'] as $c):?><td><?=e($r[$c]??'')?></td><?php endforeach;?><td class="text-nowrap"><?php if(!$meta['read_only'] && $meta['has_id']):?><a class="btn btn-sm btn-outline-primary" href="create.php?e=<?=urlencode($e)?>&id=<?=e($r['id'])?>">Edit</a><form method="post" action="delete.php" class="d-inline"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="e" value="<?=e($e)?>"><input type="hidden" name="id" value="<?=e($r['id'])?>"><button class="btn btn-sm btn-outline-danger" onclick="return confirm('Delete this record?')">Delete</button></form><?php else: ?><span class="text-muted">View</span><?php endif;?></td></tr><?php endforeach;?>
<?php if(!$rows):?><tr><td colspan="99" class="text-center py-5 text-muted">No records found.</td></tr><?php endif;?></tbody></table></div>
<?php $pages=max(1,(int)ceil($total/$limit));if($pages>1):?><nav class="mt-3"><ul class="pagination"><?php for($i=1;$i<=$pages;$i++):?><li class="page-item <?=($i===$page?'active':'')?>"><a class="page-link" href="?e=<?=urlencode($e)?>&q=<?=urlencode($search)?>&page=<?=$i?>&limit=<?=$limit?>"><?=$i?></a></li><?php endfor;?></ul></nav><?php endif;page_bottom(); ?>